"""
Portal Client - Unified communication layer for Droidrun Portal app.

This module provides automatic TCP/Content Provider fallback for Portal communication.
"""

import asyncio
import base64
import io
import json
import logging
import re
from typing import Any, Dict, List, Optional
from urllib.parse import urlparse, urlunparse

import httpx
from async_adbutils import AdbDevice

logger = logging.getLogger("droidrun")

PORTAL_REMOTE_PORT = 8080  # Port on device where Portal HTTP server runs


def validate_android_portal_url(
    url: str,
    default_port: int = PORTAL_REMOTE_PORT,
) -> str:
    """Validate and normalize an Android portal base URL."""
    normalized = url.strip().rstrip("/")
    if not normalized:
        raise ValueError(
            "Android portal URL cannot be empty. Provide a host[:port] or http(s) URL."
        )

    if "://" not in normalized:
        normalized = f"http://{normalized}"

    parsed = urlparse(normalized)
    if parsed.scheme not in {"http", "https"} or not parsed.hostname:
        raise ValueError(
            "Android portal URL must be a valid http(s) URL, e.g. http://192.168.1.10:8080"
        )

    host = parsed.hostname
    port = parsed.port or default_port
    path = parsed.path.rstrip("/")
    return urlunparse((parsed.scheme, f"{host}:{port}", path, "", "", ""))


class PortalClient:
    """
    Unified client for Droidrun Portal communication.

    Automatically handles TCP vs Content Provider fallback with the following strategy:
    - On init, checks for existing port forward and reuses it
    - If no forward exists, creates new one
    - Tests connection and sets tcp_available flag
    - All methods auto-select TCP or content provider based on availability
    - Port forwards persist until device disconnect (no explicit cleanup needed)

    Key features:
    - Reuses existing port forwards (no cleanup needed)
    - Automatic fallback to content provider if TCP fails
    - Zero explicit resource management
    - Graceful degradation

    Note: TCP mode is significantly faster but requires ADB port forwarding.
    Content provider mode works without port forwarding but has higher latency.
    """

    # 教程注释：PortalClient 是 Android 通信总入口，对上层提供“统一方法 + 自动通道回退”。

    def __init__(
        self,
        device: AdbDevice | None = None,
        prefer_tcp: bool = False,
        base_url: str | None = None,
        auth_token: str | None = None,
        timeout: float = 10.0,
    ):
        """
        Initialize Portal client.

        Args:
            device: Optional ADB device instance
            prefer_tcp: Whether to prefer TCP communication (will fallback to content provider if unavailable)
            base_url: Direct portal base URL for no-ADB mode
            auth_token: Direct portal auth token for HTTP requests
            timeout: Default HTTP timeout in seconds

        Note:
            Call `await client.connect()` after initialization to establish connection.
        """
        self.device = device
        self.prefer_tcp = prefer_tcp or base_url is not None
        self.tcp_available = False
        self.tcp_base_url = validate_android_portal_url(base_url) if base_url else None
        self.local_tcp_port = None
        self._auth_token: Optional[str] = auth_token
        self._timeout = timeout
        self._connected = False

    async def connect(self) -> None:
        """
        Establish connection...
        """
        if self._connected:
            return

        if self.tcp_base_url is not None:
            if not await self._test_connection():
                raise ConnectionError(
                    f"Could not connect to Android portal at {self.tcp_base_url}. "
                    "Make sure the Portal HTTP server is enabled and reachable."
                )
            self.tcp_available = True
            self._connected = True
            return

        if self.prefer_tcp:
            await self._try_enable_tcp()

        self._connected = True

    async def _ensure_connected(self) -> None:
        """Check if connected, raise error if not."""
        if not self._connected:
            await self.connect()

    async def _fetch_auth_token(self) -> Optional[str]:
        """Fetch the auth token from the Portal via the content provider.

        The Portal HTTP server requires a Bearer token for all requests.
        The token is generated by the Portal app and exposed via the content
        provider, which is only accessible over ADB (secure channel).

        Returns:
            The auth token string, or None if unavailable.
        """
        if self.device is None:
            return self._auth_token

        try:
            output = await self.device.shell(
                "content query --uri content://com.droidrun.portal/auth_token"
            )
            data = self._parse_content_provider_output(output)
            if data is None:
                logger.debug("Auth token: unparseable content provider output")
                return None

            # Extract token — handle various response shapes
            token = None
            if isinstance(data, dict):
                token = (
                    data.get("token")
                    or data.get("auth_token")
                    or data.get("result")
                    or data.get("data")
                )
                # Unwrap nested dict: {"status": "success", "result": {"token": "..."}}
                if isinstance(token, dict):
                    token = token.get("token") or token.get("auth_token")
            elif isinstance(data, str):
                token = data

            if token and isinstance(token, str):
                logger.debug("Auth token retrieved from Portal")
                return token

            logger.debug(f"Auth token: unexpected response format: {data}")
            return None
        except Exception as e:
            logger.debug(f"Failed to fetch auth token: {e}")
            return None

    @property
    def _tcp_headers(self) -> Dict[str, str]:
        """HTTP headers for all TCP requests, including auth when available."""
        headers: Dict[str, str] = {}
        if self._auth_token:
            headers["Authorization"] = f"Bearer {self._auth_token}"
        return headers

    async def _try_enable_tcp(self) -> None:
        """
        Try to enable TCP communication. Fails silently and falls back to content provider.

        Strategy:
        1. Fetch auth token via content provider (secure ADB channel)
        2. Check if port forward already exists → reuse
        3. If not, create new forward
        4. Test connection with authenticated ping
        5. Set tcp_available flag
        """
        # 教程注释：这里实现 TCP 优先策略，失败时不会中断流程，而是自动降级到 content provider。
        try:
            # Step 1: Fetch auth token before any HTTP calls
            self._auth_token = await self._fetch_auth_token()
            if not self._auth_token:
                logger.debug(
                    "No auth token available — Portal may not require auth, "
                    "proceeding without it"
                )

            # Step 2: Check for existing forward
            local_port = await self._find_existing_forward()

            # Step 3: If no forward exists, create one
            if local_port is None:
                logger.debug(
                    f"No existing forward found, creating new forward for port {PORTAL_REMOTE_PORT}"
                )
                local_port = await self.device.forward_port(PORTAL_REMOTE_PORT)
                logger.debug(
                    f"Created forward: localhost:{local_port} -> device:{PORTAL_REMOTE_PORT}"
                )
            else:
                logger.debug(
                    f"Reusing existing forward: localhost:{local_port} -> device:{PORTAL_REMOTE_PORT}"
                )

            # Store local port
            self.local_tcp_port = local_port

            # Step 4: Test connection with auth
            self.tcp_base_url = f"http://localhost:{local_port}"
            if await self._test_connection():
                self.tcp_available = True
                logger.debug(f"✓ TCP mode enabled: {self.tcp_base_url}")
            else:
                # Step 4b: Try enabling the HTTP server via content provider
                logger.debug("TCP ping failed, trying to enable Portal HTTP server...")
                await self.device.shell(
                    "content insert --uri content://com.droidrun.portal/toggle_socket_server --bind enabled:b:true"
                )
                await asyncio.sleep(1)

                # Re-fetch token — server restart may generate a new one
                new_token = await self._fetch_auth_token()
                if new_token:
                    self._auth_token = new_token

                if await self._test_connection():
                    self.tcp_available = True
                    logger.debug(
                        f"✓ TCP mode enabled after starting server: {self.tcp_base_url}"
                    )
                else:
                    logger.warning("TCP unavailable, using content provider fallback")
                    self.tcp_available = False

        except Exception as e:
            logger.warning(f"TCP unavailable ({e}), using content provider fallback")
            self.tcp_available = False

    async def _find_existing_forward(self) -> Optional[int]:
        """
        Check if a forward already exists for the Portal remote port.

        Returns:
            Local port number if forward exists, None otherwise
        """
        if self.device is None:
            return None

        try:
            forwards = []
            async for forward in self.device.forward_list():
                forwards.append(forward)
            # forwards is a list of ForwardItem objects with serial, local, remote attributes
            for forward in forwards:
                if (
                    forward.serial == self.device.serial
                    and forward.remote == f"tcp:{PORTAL_REMOTE_PORT}"
                ):
                    # Extract local port from "tcp:12345"
                    match = re.search(r"tcp:(\d+)", forward.local)
                    if match:
                        local_port = int(match.group(1))
                        logger.debug(
                            f"Found existing forward: localhost:{local_port} -> {PORTAL_REMOTE_PORT}"
                        )
                        return local_port
        except Exception as e:
            logger.debug(f"Failed to check existing forwards: {e}")

        return None

    async def _tcp_request(
        self,
        client: httpx.AsyncClient,
        method: str,
        url: str,
        extra_headers: Optional[Dict[str, str]] = None,
        **kwargs,
    ) -> httpx.Response:
        """Make an authenticated TCP request, re-fetching the token once on 401/403.

        This is the single choke-point for all TCP HTTP traffic so that token
        rotation is handled uniformly rather than duplicated per call-site.

        Args:
            client: Shared httpx.AsyncClient for the request.
            method: HTTP method string ("GET", "POST", …).
            url: Full URL to request.
            extra_headers: Additional headers merged on top of auth headers
                           (e.g. ``{"Content-Type": "application/json"}``).
            **kwargs: Passed straight through to ``client.request()``.

        Returns:
            The httpx.Response (possibly from the retry attempt).
        """
        # 教程注释：统一封装鉴权失败重试，避免每个调用点重复处理 token 轮换。
        headers = {**self._tcp_headers, **(extra_headers or {})}
        response = await client.request(method, url, headers=headers, **kwargs)

        if response.status_code in (401, 403):
            logger.debug(
                f"TCP auth rejected ({response.status_code}), re-fetching token..."
            )
            self._auth_token = await self._fetch_auth_token()
            if self._auth_token:
                headers = {**self._tcp_headers, **(extra_headers or {})}
                response = await client.request(method, url, headers=headers, **kwargs)

        return response

    @staticmethod
    def _unwrap_tcp_payload(data: Any) -> Any:
        """Unwrap the standard ApiResponse envelope returned by Portal HTTP."""
        if isinstance(data, dict):
            if data.get("status") == "error":
                raise ConnectionError(data.get("error") or data.get("message") or str(data))

            inner_key = (
                "result"
                if "result" in data
                else "data" if "data" in data else None
            )
            if inner_key is not None:
                return data[inner_key]

        return data

    async def _request_json_tcp(
        self,
        method: str,
        path: str,
        payload: Optional[Dict[str, Any]] = None,
        timeout: Optional[float] = None,
    ) -> Any:
        """Perform a JSON HTTP request against the Portal TCP endpoint."""
        await self._ensure_connected()
        if not self.tcp_available or not self.tcp_base_url:
            raise ConnectionError("Portal HTTP server is not available")

        kwargs: Dict[str, Any] = {}
        extra_headers: Optional[Dict[str, str]] = None
        if payload is not None:
            kwargs["json"] = payload
            extra_headers = {"Content-Type": "application/json"}

        async with httpx.AsyncClient() as client:
            response = await self._tcp_request(
                client,
                method,
                f"{self.tcp_base_url}{path}",
                extra_headers=extra_headers,
                timeout=timeout or self._timeout,
                **kwargs,
            )

        if response.status_code != 200:
            raise ConnectionError(
                f"Portal request failed for {path}: HTTP {response.status_code}: {response.text}"
            )

        try:
            data = response.json() if response.content else {}
        except Exception as exc:
            raise ConnectionError(
                f"Portal returned a non-JSON response for {path}"
            ) from exc

        return self._unwrap_tcp_payload(data)

    async def _request_binary_tcp(
        self,
        path: str,
        timeout: Optional[float] = None,
    ) -> bytes:
        """Perform a binary GET request against the Portal TCP endpoint."""
        await self._ensure_connected()
        if not self.tcp_available or not self.tcp_base_url:
            raise ConnectionError("Portal HTTP server is not available")

        async with httpx.AsyncClient() as client:
            response = await self._tcp_request(
                client,
                "GET",
                f"{self.tcp_base_url}{path}",
                timeout=timeout or self._timeout,
            )

        if response.status_code != 200:
            raise ConnectionError(
                f"Portal request failed for {path}: HTTP {response.status_code}: {response.text}"
            )

        content_type = response.headers.get("content-type", "")
        if content_type.startswith("image/"):
            return response.content

        try:
            data = response.json() if response.content else {}
            payload = self._unwrap_tcp_payload(data)
            if isinstance(payload, str):
                return base64.b64decode(payload)
        except Exception as exc:
            raise ConnectionError(
                f"Portal returned an unexpected binary response for {path}"
            ) from exc

        raise ConnectionError(f"Portal did not return binary data for {path}")

    async def _test_connection(self) -> bool:
        """Test if TCP connection to Portal is working (with auth)."""
        try:
            async with httpx.AsyncClient() as client:
                response = await self._tcp_request(
                    client, "GET", f"{self.tcp_base_url}/ping", timeout=5
                )
                return response.status_code == 200
        except Exception as e:
            logger.debug(f"TCP connection test failed: {e}")
            return False

    def _parse_content_provider_output(
        self, raw_output: str
    ) -> Optional[Dict[str, Any]]:
        """
        Parse the raw ADB content provider output and extract JSON data.

        Args:
            raw_output: Raw output from ADB content query command

        Returns:
            Parsed JSON data or None if parsing failed
        """
        lines = raw_output.strip().split("\n")

        # Try line-by-line parsing
        for line in lines:
            line = line.strip()

            # Look for "result=" pattern (common content provider format)
            if "result=" in line:
                result_start = line.find("result=") + 7
                json_str = line[result_start:]
                try:
                    json_data = json.loads(json_str)
                    # Handle nested "result" or "data" field with JSON string (backward compatible)
                    if isinstance(json_data, dict):
                        # Check for 'result' first (new portal format), then 'data' (legacy)
                        inner_key = (
                            "result"
                            if "result" in json_data
                            else "data" if "data" in json_data else None
                        )
                        if inner_key:
                            inner_value = json_data[inner_key]
                            if isinstance(inner_value, str):
                                try:
                                    return json.loads(inner_value)
                                except json.JSONDecodeError:
                                    return inner_value
                            return inner_value
                    return json_data
                except json.JSONDecodeError:
                    continue

            # Fallback: try lines starting with JSON
            elif line.startswith("{") or line.startswith("["):
                try:
                    return json.loads(line)
                except json.JSONDecodeError:
                    continue

        # Last resort: try parsing entire output
        try:
            return json.loads(raw_output.strip())
        except json.JSONDecodeError:
            return None

    async def get_state(self) -> Dict[str, Any]:
        """
        Get device state (accessibility tree + phone state).
        Auto-selects TCP or content provider.

        Returns:
            Dictionary containing 'a11y_tree' and 'phone_state' keys
        """
        # 教程注释：状态读取优先走 TCP，高性能；不可用时自动走 content provider 保底。
        await self._ensure_connected()
        if self.tcp_available:
            return await self._get_state_tcp()
        return await self._get_state_content_provider()

    async def _get_state_tcp(self) -> Dict[str, Any]:
        """Get state via TCP."""
        try:
            data = await self._request_json_tcp("GET", "/state_full", timeout=10)
            if isinstance(data, str):
                return json.loads(data)
            if isinstance(data, dict):
                return data
            raise ConnectionError(f"Unexpected state payload type: {type(data).__name__}")
        except Exception as e:
            if self.device is None:
                raise ConnectionError(f"Portal state request failed: {e}") from e
            logger.debug(f"TCP get_state error: {e}, using fallback")
            return await self._get_state_content_provider()

    async def _get_state_content_provider(self) -> Dict[str, Any]:
        """Get state via content provider (fallback)."""
        try:
            output = await self.device.shell(
                "content query --uri content://com.droidrun.portal/state_full"
            )
            state_data = self._parse_content_provider_output(output)

            if state_data is None:
                return {
                    "error": "Parse Error",
                    "message": "Failed to parse state data from ContentProvider",
                }

            # Handle nested "result" or "data" field if present (backward compatible)
            if isinstance(state_data, dict):
                # Check for 'result' first (new portal format), then 'data' (legacy)
                inner_key = (
                    "result"
                    if "result" in state_data
                    else "data" if "data" in state_data else None
                )
                if inner_key:
                    inner_value = state_data[inner_key]
                    if isinstance(inner_value, str):
                        try:
                            return json.loads(inner_value)
                        except json.JSONDecodeError:
                            return {
                                "error": "Parse Error",
                                "message": "Failed to parse nested JSON data",
                            }
                    elif isinstance(inner_value, dict):
                        return inner_value

            return state_data

        except Exception as e:
            return {"error": "ContentProvider Error", "message": str(e)}

    async def input_text(self, text: str, clear: bool = False) -> bool:
        """
        Input text via keyboard.
        Auto-selects TCP or content provider.

        Args:
            text: Text to input
            clear: Whether to clear existing text first

        Returns:
            True if successful, False otherwise
        """
        # 教程注释：文本输入同样使用双通道策略，尽量保证在弱网络或服务异常时仍可输入。
        await self._ensure_connected()
        if self.tcp_available:
            return await self._input_text_tcp(text, clear)
        return await self._input_text_content_provider(text, clear)

    async def _input_text_tcp(self, text: str, clear: bool) -> bool:
        """Input text via TCP."""
        try:
            encoded = base64.b64encode(text.encode()).decode()
            payload = {"base64_text": encoded, "clear": clear}
            await self._request_json_tcp("POST", "/keyboard/input", payload, timeout=10)
            logger.debug("TCP input_text successful")
            return True
        except Exception as e:
            if self.device is None:
                logger.debug(f"TCP input_text error in direct mode: {e}")
                return False
            logger.debug(f"TCP input_text error: {e}, using fallback")
            return await self._input_text_content_provider(text, clear)

    async def _input_text_content_provider(self, text: str, clear: bool) -> bool:
        """Input text via content provider (fallback)."""
        try:
            encoded = base64.b64encode(text.encode()).decode()
            clear_str = "true" if clear else "false"
            cmd = (
                f'content insert --uri "content://com.droidrun.portal/keyboard/input" '
                f'--bind base64_text:s:"{encoded}" '
                f"--bind clear:b:{clear_str}"
            )
            await self.device.shell(cmd)
            logger.debug("Content provider input_text successful")
            return True
        except Exception as e:
            logger.error(f"Content provider input_text error: {e}")
            return False

    async def take_screenshot(self, hide_overlay: bool = True) -> bytes:
        """
        Take screenshot of device.
        Auto-selects TCP or ADB screencap.

        Args:
            hide_overlay: Whether to hide Portal overlay during screenshot

        Returns:
            Screenshot image bytes (PNG format)
        """
        # 教程注释：截图优先使用 Portal TCP 返回结构化响应，失败即回退 ADB screencap。
        await self._ensure_connected()
        if self.tcp_available:
            return await self._take_screenshot_tcp(hide_overlay)
        return await self._take_screenshot_adb()

    async def _take_screenshot_tcp(self, hide_overlay: bool) -> bytes:
        """Take screenshot via TCP."""
        try:
            path = "/screenshot" if hide_overlay else "/screenshot?hideOverlay=false"
            logger.debug("Screenshot taken via TCP")
            return await self._request_binary_tcp(path, timeout=10.0)
        except Exception as e:
            if self.device is None:
                raise ConnectionError(f"TCP screenshot failed in direct mode: {e}") from e
            logger.debug(f"TCP screenshot error: {e}, using fallback")
            return await self._take_screenshot_adb()

    async def _take_screenshot_adb(self) -> bytes:
        """Take screenshot via ADB screencap (fallback)."""
        data = await self.device.screenshot_bytes()
        logger.debug("Screenshot taken via ADB")
        return data

    async def get_apps(self, include_system: bool = True) -> List[Dict[str, str]]:
        """
        Get installed apps with package name and label.

        Note: Currently only supports content provider (no TCP endpoint exists yet)

        Args:
            include_system: Whether to include system apps

        Returns:
            List of dicts with 'package' and 'label' keys
        """
        await self._ensure_connected()
        try:
            if self.tcp_available:
                logger.debug("Getting apps via TCP")
                packages_data = await self._request_json_tcp("GET", "/packages", timeout=10)
            elif self.device is not None:
                logger.debug("Getting apps via content provider")
                output = await self.device.shell(
                    "content query --uri content://com.droidrun.portal/packages"
                )
                packages_data = self._parse_content_provider_output(output)
            else:
                raise ConnectionError("Portal apps endpoint is not available")

            if not packages_data:
                logger.warning("No packages data found in content provider response")
                return []

            # Handle both formats:
            # - New format: array directly (via RawArray -> result: [...])
            # - Legacy format: wrapped in {"packages": [...]}
            packages_list = None
            if isinstance(packages_data, list):
                # New format: packages_data is already the list
                packages_list = packages_data
            elif isinstance(packages_data, dict):
                if "packages" in packages_data:
                    # Legacy format: wrapped in {"packages": [...]}
                    packages_list = packages_data["packages"]
                else:
                    # May be wrapped in result/data
                    inner_key = (
                        "result"
                        if "result" in packages_data
                        else "data" if "data" in packages_data else None
                    )
                    if inner_key:
                        inner_value = packages_data[inner_key]
                        if isinstance(inner_value, list):
                            packages_list = inner_value
                        elif (
                            isinstance(inner_value, dict) and "packages" in inner_value
                        ):
                            packages_list = inner_value["packages"]

            if not packages_list:
                logger.warning("Could not extract packages list from response")
                return []

            # Filter and format apps
            apps = []
            for package_info in packages_list:
                if not include_system and package_info.get("isSystemApp", False):
                    continue

                apps.append(
                    {
                        "package": package_info.get("packageName", ""),
                        "label": package_info.get("label", ""),
                    }
                )

            logger.debug(f"Found {len(apps)} apps")
            return apps

        except Exception as e:
            logger.error(f"Error getting apps: {e}")
            raise ValueError(f"Error getting apps: {e}") from e

    async def get_version(self) -> str:
        """Get Portal app version."""
        await self._ensure_connected()
        if self.tcp_available:
            try:
                return str(await self._request_json_tcp("GET", "/version", timeout=5.0))
            except Exception:
                pass

        # Fallback to content provider
        if self.device is None:
            return "unknown"
        try:
            output = await self.device.shell(
                "content query --uri content://com.droidrun.portal/version"
            )
            result = self._parse_content_provider_output(output)
            if result:
                # Check for 'result' first (new portal format), then 'data' (legacy)
                inner_key = (
                    "result"
                    if "result" in result
                    else "data" if "data" in result else None
                )
                if inner_key:
                    return result[inner_key]
        except Exception:
            pass

        return "unknown"

    async def get_time(self) -> str:
        """Get Portal time endpoint as a string."""
        await self._ensure_connected()

        if self.tcp_available:
            try:
                result = await self._request_json_tcp("POST", "/time", {}, timeout=5.0)
                return str(result)
            except Exception as e:
                if self.device is None:
                    raise ConnectionError(
                        f"Portal time endpoint is not available: {e}"
                    ) from e
                logger.debug(f"TCP get_time error: {e}, using fallback")

        if self.device is not None:
            # Fallback 1: content provider time endpoint.
            try:
                output = await self.device.shell(
                    "content query --uri content://com.droidrun.portal/time"
                )
                result = self._parse_content_provider_output(output)
                if result is not None:
                    return str(result)
            except Exception as e:
                logger.debug(f"Content provider get_time error: {e}")

            # Fallback 2: device shell date command.
            try:
                output = await self.device.shell('date "+%Y-%m-%d %H:%M:%S"')
                value = (output or "").strip().splitlines()[-1].strip()
                if value:
                    return value
            except Exception as e:
                logger.debug(f"Shell date fallback error: {e}")

        raise ConnectionError("Portal HTTP server is not available")

    async def tap(self, x: int, y: int) -> None:
        """Perform a tap through the Portal action endpoint."""
        await self._request_json_tcp("POST", "/tap", {"x": x, "y": y}, timeout=10.0)

    async def swipe(
        self,
        start_x: int,
        start_y: int,
        end_x: int,
        end_y: int,
        duration_ms: float = 1000,
    ) -> None:
        """Perform a swipe through the Portal action endpoint."""
        await self._request_json_tcp(
            "POST",
            "/swipe",
            {
                "startX": start_x,
                "startY": start_y,
                "endX": end_x,
                "endY": end_y,
                "duration": int(duration_ms),
            },
            timeout=max(10.0, duration_ms / 1000 + 2),
        )

    async def perform_global_action(self, action: int) -> Any:
        """Perform an accessibility global action through Portal."""
        return await self._request_json_tcp(
            "POST",
            "/global",
            {"action": action},
            timeout=10.0,
        )

    async def press_key(self, key_code: int) -> Any:
        """Dispatch a keyboard key event through Portal."""
        return await self._request_json_tcp(
            "POST",
            "/keyboard/key",
            {"key_code": key_code},
            timeout=10.0,
        )

    async def start_app(
        self,
        package: str,
        activity: Optional[str] = None,
        stop_before_launch: bool = False,
    ) -> Any:
        """Start an app through the Portal action endpoint."""
        payload: Dict[str, Any] = {
            "package": package,
            "stopBeforeLaunch": stop_before_launch,
        }
        if activity:
            payload["activity"] = activity
        return await self._request_json_tcp("POST", "/app", payload, timeout=10.0)

    async def stop_app(self, package: str) -> Any:
        """Stop an app through the Portal action endpoint."""
        return await self._request_json_tcp(
            "POST",
            "/app/stop",
            {"package": package},
            timeout=10.0,
        )

    async def ping(self) -> Dict[str, Any]:
        """
        Test Portal connection and verify state availability.

        Returns:
            Dictionary with status and connection details
        """
        await self._ensure_connected()
        if self.tcp_available:
            try:
                async with httpx.AsyncClient() as client:
                    response = await self._tcp_request(
                        client, "GET", f"{self.tcp_base_url}/ping", timeout=5.0
                    )
                    if response.status_code == 200:
                        try:
                            tcp_response = response.json() if response.content else {}
                            result = {
                                "status": "success",
                                "method": "tcp",
                                "url": self.tcp_base_url,
                                "response": tcp_response,
                            }
                        except json.JSONDecodeError:
                            result = {
                                "status": "success",
                                "method": "tcp",
                                "url": self.tcp_base_url,
                                "response": response.text,
                            }
                    else:
                        return {
                            "status": "error",
                            "method": "tcp",
                            "message": f"HTTP {response.status_code}: {response.text}",
                        }
            except Exception as e:
                return {"status": "error", "method": "tcp", "message": str(e)}
        else:
            # Test content provider
            try:
                output = await self.device.shell(
                    "content query --uri content://com.droidrun.portal/state_full"
                )
                if "Row: 0 result=" in output:
                    result = {"status": "success", "method": "content_provider"}
                else:
                    return {
                        "status": "error",
                        "method": "content_provider",
                        "message": "Invalid response",
                    }
            except Exception as e:
                return {
                    "status": "error",
                    "method": "content_provider",
                    "message": str(e),
                }

        # Verify state has the required keys
        try:
            state = await self.get_state()
            required = ("a11y_tree", "phone_state", "device_context")
            missing = [k for k in required if k not in state]
            if missing:
                return {
                    "status": "error",
                    "method": result.get("method", "unknown"),
                    "message": f"incompatible portal — missing {', '.join(missing)}",
                }
        except Exception as e:
            return {
                "status": "error",
                "method": result.get("method", "unknown"),
                "message": f"state check failed: {e}",
            }

        return result
